# Generated by Django 3.1.4 on 2021-01-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='special_item',
            field=models.CharField(default='No', max_length=64),
        ),
        migrations.AlterField(
            model_name='storageingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='api.ingredient'),
        ),
    ]
