# Generated by Django 3.1.4 on 2021-01-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210116_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='Cooking_time',
            field=models.IntegerField(default=0),
        ),
    ]
