# Generated by Django 3.1.4 on 2021-01-17 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210117_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='Cooking_time',
            new_name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='special_item',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='eatable_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity2', to='api.ingredient'),
        ),
        migrations.CreateModel(
            name='User_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('schedule', models.ManyToManyField(default=None, to='api.Daily_Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='daily_schedule',
            name='meal',
            field=models.ManyToManyField(default=None, to='api.Meal'),
        ),
    ]
