# Generated by Django 3.1.4 on 2021-01-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210117_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_schedule',
            old_name='meal',
            new_name='meals',
        ),
    ]
