# Generated by Django 3.1.4 on 2021-01-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210117_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_schedule',
            name='meals',
        ),
        migrations.AddField(
            model_name='daily_schedule',
            name='meal',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='api.meal'),
        ),
    ]
