# Generated by Django 3.1.4 on 2021-01-17 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210117_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_schedule',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
