# Generated by Django 3.1.4 on 2021-01-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('special_item', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('Cooking_time', models.TimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Storageingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food_storage')),
            ],
        ),
        migrations.CreateModel(
            name='Mealingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.ManyToManyField(default=None, related_name='recipes', through='api.Mealingredient', to='api.Ingredient'),
        ),
        migrations.AddField(
            model_name='food_storage',
            name='Ingredients',
            field=models.ManyToManyField(default=None, related_name='Users', through='api.Storageingredient', to='api.Ingredient'),
        ),
    ]
