# Generated by Django 3.1.4 on 2021-01-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storageingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
